### ISSUE TITLE
Could not load js config file /srv/app/node_modules/@strapi/plugin-upload/strapi-server.js: 

### ISSUE THREAD

**Issue by Gezellligheid** [strapi/strapi-plugin-seo#14]
After the installation of the Strapi-SEO plugin and after a build ofcourse (Executed commands under here), 
```
yarn add @strapi/plugin-seo
yarn build
```

I was greeted with the following message on start:
```
Starting your app (with develop)...
[2022-06-21 11:39:54.429] debug: ⛔️ Server wasn't able to start properly.
[2022-06-21 11:39:54.430] error: Could not load js config file /srv/app/node_modules/@strapi/plugin-upload/strapi-server.js: 
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-linux-x64.node'

Require stack:
- /srv/app/node_modules/sharp/lib/sharp.js
- /srv/app/node_modules/sharp/lib/constructor.js
- /srv/app/node_modules/sharp/lib/index.js
- /srv/app/node_modules/@strapi/plugin-upload/server/services/image-manipulation.js
- /srv/app/node_modules/@strapi/plugin-upload/server/services/index.js
- /srv/app/node_modules/@strapi/plugin-upload/server/index.js
- /srv/app/node_modules/@strapi/plugin-upload/strapi-server.js
- /srv/app/node_modules/@strapi/strapi/lib/core/app-configuration/load-config-file.js
- /srv/app/node_modules/@strapi/strapi/lib/core/app-configuration/config-loader.js
- /srv/app/node_modules/@strapi/strapi/lib/core/app-configuration/index.js
- /srv/app/node_modules/@strapi/strapi/lib/commands/develop.js
- /usr/local/share/.config/yarn/global/node_modules/@strapi/strapi/bin/strapi.js


Possible solutions:
- Install with the --verbose flag and look for errors: "npm install --ignore-scripts=false --verbose sharp"
- Install for the current linux-x64 runtime: "npm install --platform=linux --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install

Error: Could not load js config file /srv/app/node_modules/@strapi/plugin-upload/strapi-server.js: 
Something went wrong installing the "sharp" module
Cannot find module '../build/Release/sharp-linux-x64.node'

Require stack:
- /srv/app/node_modules/sharp/lib/sharp.js
- /srv/app/node_modules/sharp/lib/constructor.js
- /srv/app/node_modules/sharp/lib/index.js
- /srv/app/node_modules/@strapi/plugin-upload/server/services/image-manipulation.js
- /srv/app/node_modules/@strapi/plugin-upload/server/services/index.js
- /srv/app/node_modules/@strapi/plugin-upload/server/index.js
- /srv/app/node_modules/@strapi/plugin-upload/strapi-server.js
- /srv/app/node_modules/@strapi/strapi/lib/core/app-configuration/load-config-file.js
- /srv/app/node_modules/@strapi/strapi/lib/core/app-configuration/config-loader.js
- /srv/app/node_modules/@strapi/strapi/lib/core/app-configuration/index.js
- /srv/app/node_modules/@strapi/strapi/lib/commands/develop.js
- /usr/local/share/.config/yarn/global/node_modules/@strapi/strapi/bin/strapi.js

Possible solutions:
- Install with the --verbose flag and look for errors: "npm install --ignore-scripts=false --verbose sharp"
- Install for the current linux-x64 runtime: "npm install --platform=linux --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at loadJsFile (/srv/app/node_modules/@strapi/strapi/lib/core/app-configuration/load-config-file.js:18:11)
    at loadFile (/srv/app/node_modules/@strapi/strapi/lib/core/app-configuration/load-config-file.js:35:14)
    at Object.loadPlugins (/srv/app/node_modules/@strapi/strapi/lib/core/loaders/plugins/index.js:96:26)
    at async Strapi.loadPlugins (/srv/app/node_modules/@strapi/strapi/lib/Strapi.js:290:5)
    at async Promise.all (index 2)
    at async Strapi.register (/srv/app/node_modules/@strapi/strapi/lib/Strapi.js:326:5)
    at async Strapi.load (/srv/app/node_modules/@strapi/strapi/lib/Strapi.js:425:5)
    at async Strapi.start (/srv/app/node_modules/@strapi/strapi/lib/Strapi.js:169:9)
```

I tried installing `sharp` aswel, just like it mentioned.
But I just got the same issue. Even with `linux` and `x64` declared in the package.json
Using Yarn

**Comment by Mcastres** [comment]
Hello @Gezellligheid 👋 I think it has nothing to do with this plugin but with sharp and your OS here.
You can try to open a thread on our forum if you need help with this topic :)
