### ISSUE TITLE
npm i @strapi/plugin-seo generates error: npm ERR! code EUNSUPPORTEDPROTOCOL npm ERR! Unsupported URL Type "workspace:": workspace:*

### ISSUE THREAD

**Issue by piotrsliwka333** [strapi/strapi-plugin-seo#82]
## Bug report

- Node.js version: 20.10.0
- NPM version: 10.2.3
- Strapi version: 5.0.5
- Database: Strapi default
- Operating system: wsl2
- Is your project Javascript or Typescript: Typescript

### Describe the bug
After instaling plugin error below appear
![image](https://github.com/user-attachments/assets/f283f4e2-d302-4da0-9314-3ee46cb98eed)

error log from the file
/home/piotr/.npm/_logs/2024-10-14T14_40_02_342Z-debug-0.log
```
0 verbose cli /home/piotr/.nvm/versions/node/v20.10.0/bin/node /home/piotr/.nvm/versions/node/v20.10.0/bin/npm
1 info using npm@10.2.3
2 info using node@v20.10.0
3 timing npm:load:whichnode Completed in 13ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/home/piotr/.nvm/versions/node/v20.10.0/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/home/piotr/Projects/nextjs/strapi-v5/backend/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/home/piotr/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/home/piotr/.nvm/versions/node/v20.10.0/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 5ms
17 timing npm:load:configload Completed in 5ms
18 timing config:load:flatten Completed in 2ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 1ms
21 verbose title npm i @strapi/plugin-seo
22 verbose argv "i" "@strapi/plugin-seo"
23 timing npm:load:setTitle Completed in 0ms
24 timing npm:load:display Completed in 1ms
25 verbose logfile logs-max:10 dir:/home/piotr/.npm/_logs/2024-10-14T14_40_02_342Z-
26 verbose logfile /home/piotr/.npm/_logs/2024-10-14T14_40_02_342Z-debug-0.log
27 timing npm:load:logFile Completed in 6ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 36ms
31 timing arborist:ctor Completed in 1ms
32 silly logfile start cleaning logs, removing 1 files
33 silly logfile done cleaning log files
34 timing idealTree:init Completed in 672ms
35 timing idealTree:userRequests Completed in 1ms
36 silly idealTree buildDeps
37 silly fetch manifest @strapi/plugin-seo@^2.0.0
38 timing arborist:ctor Completed in 0ms
39 http fetch GET 200 https://registry.npmjs.org/@strapi%2fplugin-seo 793ms (cache revalidated)
40 silly fetch manifest @strapi/strapi@^5.0.5
41 http fetch GET 200 https://registry.npmjs.org/@strapi%2fstrapi 175ms (cache updated)
42 timing idealTree Completed in 1674ms
43 timing command:i Completed in 1682ms
44 verbose stack Error: Unsupported URL Type "workspace:": workspace:*
44 verbose stack     at unsupportedURLType (/home/piotr/.nvm/versions/node/v20.10.0/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:310:15)
44 verbose stack     at fromURL (/home/piotr/.nvm/versions/node/v20.10.0/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:367:13)
44 verbose stack     at Function.resolve (/home/piotr/.nvm/versions/node/v20.10.0/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:83:12)
44 verbose stack     at #nodeFromEdge (/home/piotr/.nvm/versions/node/v20.10.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1058:37)
44 verbose stack     at async #loadPeerSet (/home/piotr/.nvm/versions/node/v20.10.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1321:23)
44 verbose stack     at async #buildDepStep (/home/piotr/.nvm/versions/node/v20.10.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:917:11)
44 verbose stack     at async Arborist.buildIdealTree (/home/piotr/.nvm/versions/node/v20.10.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:196:7)
44 verbose stack     at async Promise.all (index 1)
44 verbose stack     at async Arborist.reify (/home/piotr/.nvm/versions/node/v20.10.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
44 verbose stack     at async Install.exec (/home/piotr/.nvm/versions/node/v20.10.0/lib/node_modules/npm/lib/commands/install.js:152:5)
45 verbose cwd /home/piotr/Projects/nextjs/strapi-v5/backend
46 verbose Linux 5.15.153.1-microsoft-standard-WSL2
47 verbose node v20.10.0
48 verbose npm  v10.2.3
49 error code EUNSUPPORTEDPROTOCOL
50 error Unsupported URL Type "workspace:": workspace:*
51 verbose exit 1
52 timing npm Completed in 1839ms
53 verbose unfinished npm timer reify 1728916802497
54 verbose unfinished npm timer reify:loadTrees 1728916802503
55 verbose unfinished npm timer idealTree:buildDeps 1728916803177
56 verbose unfinished npm timer idealTree:#root 1728916803177
57 verbose code 1
58 error A complete log of this run can be found in: /home/piotr/.npm/_logs/2024-10-14T14_40_02_342Z-debug-0.log
```

**Comment by reslear** [comment]
```bash
➜ npm install @strapi/plugin-seo

npm error code EUNSUPPORTEDPROTOCOL
npm error Unsupported URL Type "workspace:": workspace:*
npm error A complete log of this run can be found in: /Users/reslear/.npm/_logs/2024-10-14T15_19_47_106Z-debug-0.log
```

**Comment by Mcastres** [comment]
Closing since it has been fixed!
