### ISSUE TITLE
[BUG] Cannot destructure property 'metaTitle' of 'v.seo' as it is null.

### ISSUE THREAD

**Issue by dimitrisganotis** [strapi/strapi-plugin-seo#91]
### Required System information

- Node.js version: v20.15.1
- NPM version: v10.9.0
- Strapi version: v5.3.0
- Database: MySQL 8
- Operating system: Ubuntu 22.04
- Is your project Javascript or Typescript: Typescript
- SEO Plugin version: v2.0.2 (same issue on v2.0.3)

### Describe the bug

When I try to reset the SEO entry by pressing the delete icon, I get an error.

TypeError: Cannot destructure property 'metaTitle' of 'v.seo' as it is null.
    at ePt (https://knds-cms.thebrinkagency.com/admin/strapi-BiQYSRx3.js:3046:11903)
    at U7 (https://knds-cms.thebrinkagency.com/admin/strapi-BiQYSRx3.js:40:17031)
    at l8 (https://knds-cms.thebrinkagency.com/admin/strapi-BiQYSRx3.js:42:3143)
    at qK (https://knds-cms.thebrinkagency.com/admin/strapi-BiQYSRx3.js:42:44867)
    at UK (https://knds-cms.thebrinkagency.com/admin/strapi-BiQYSRx3.js:42:39809)
    at t6e (https://knds-cms.thebrinkagency.com/admin/strapi-BiQYSRx3.js:42:39735)
    at P3 (https://knds-cms.thebrinkagency.com/admin/strapi-BiQYSRx3.js:42:39585)
    at b8 (https://knds-cms.thebrinkagency.com/admin/strapi-BiQYSRx3.js:42:35947)
    at tF (https://knds-cms.thebrinkagency.com/admin/strapi-BiQYSRx3.js:42:36752)
    at Ed (https://knds-cms.thebrinkagency.com/admin/strapi-BiQYSRx3.js:40:3288)

### Expected behavior

I should be able to reset the data.

### Screenshots

<img width="586" alt="image" src="https://github.com/user-attachments/assets/b4d30640-6a28-45f6-8cc7-025da3783a39">

**Comment by Mcastres** [comment]
Hello @dimitrisganotis 👋 
Thanks a lot for the issue raised. This is fixed in 2.0.4 :)

Have a good one!
